baseURL = "https://ernestocid.github.io/"
languageCode = 'en-us'
title = "Ernesto Matos"
theme = "typo"

[taxonomies]
tag = 'tags'

[params]
description = "Ernesto Cid personal website"
faviconPath = 'images/laptop_emoji.png'

# Appearance settings
theme = 'light'
colorPalette = 'eink'
hideHeader = false

# Footer
showFooter = true
footerContent = "© Ernesto Matos | Powered by [Hugo](https://gohugo.io/) and [tomfran/typo](https://github.com/tomfran/typo/)"

# Intro on main page, content is markdown
homeIntroContent = """
Hello! My name is Ernesto Matos. I'm a Computer Scientist/Software Engineer living in
São Paulo, Brazil. I got a MSc and a Ph.D in computer science during
my time at [DIMAp/UFRN](http://www.dimap.ufrn.br/) (and [HHU](https://www.uni-duesseldorf.de/home/en/home.html)
in Düsseldorf for a year). During my time in
academia I did research on software testing and formal methods.

I'm currently working as an Engineering Leader at [Axonius](https://www.axonius.com/).
"""

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/ernestocid/"

[[params.social]]
name = "github"
url = "https://github.com/ernestocid"

[[params.social]]
name = "medium"
url = "https://medium.com/@ernestocid"

# Breadcrumbs
breadcrumbs = true

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "me"
url = "/me/"

[[params.menu]]
name = "blog"
url = "/blog/"

[[params.menu]]
name = "publications"
url = "/publications/"

[[params.menu]]
name = "books"
url = "/books/"

[[params.menu]]
name = "code"
url = "/code/"

[markup]
[markup.highlight]
style = 'algol'
