baseURL = "https://ernestocid.github.io/"
languageCode = 'en-us'
title = "Hi, I'm Ernesto"
theme = "typo"

[taxonomies]
tag = 'tags'

[params]
description = "Ernesto Cid personal website"
faviconPath = 'images/laptop_emoji.png'

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroContent = """
My name is Ernesto Matos. I'm a Computer Scientist/Software Engineer living in
São Paulo, Brazil. I got a MSc and a Ph.D in computer science during
my time at [DIMAp/UFRN](http://www.dimap.ufrn.br/) (and [HHU](https://www.uni-duesseldorf.de/home/en/home.html)
in Düsseldorf for a year). During my time in
academia I did research on software testing and formal methods.

I'm currently working as an Engineering Manager of the developer platform team at [Loggi](https://www.loggi.com/)
trying to reinvent logistics through technology.
"""

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/ernestocid/"

[[params.social]]
name = "github"
url = "https://github.com/ernestocid"

# Breadcrumbs
breadcrumbs = true

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "me"
url = "/me/"

[[params.menu]]
name = "blog"
url = "/blog/"

[[params.menu]]
name = "publications"
url = "/publications/"

[[params.menu]]
name = "books"
url = "/books/"

[[params.menu]]
name = "projects"
url = "/projects/"

[markup]
[markup.highlight]
style = 'algol'
